### ISSUE TITLE
Full path to /etc/rc.d/cron

### ISSUE THREAD

**Issue by paulbsd** [factorfx/OpenNAS#1]
Hi,

Could you please add these lines to /etc/rc.d/cron ?

69 - PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
96 - PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

Thanks

**Comment by cedricdenis** [comment]
Hi paulbsd,

It will be correct in next release v1.2, release very soon

Thanks
Best regards
