### ISSUE TITLE
Sample snaprepl file

### ISSUE THREAD

**Issue by paulbsd** [factorfx/OpenNAS#2]
Hi Cédric,

There isn't any sample configuration for snaprepl tool.
Could you add a sample configuration named like this : /etc/snaprepl.conf.sample

May be containing these lines if possible : 

```
localpool="SAMPLEPOOL"
remotepool="SAMPLEPOOL"
remotehost="8.8.8.8"
ssh_options="-o ConnectTimeout=5 -o Cipher=arcfour128"
notify_addr="info@test.org"
```

Thanks
Have a nice day

**Comment by cedricdenis** [comment]
Hi Paulbsd,

Allright this file will be add in next release

Thanks
