### ISSUE TITLE
Different snaprepl flavours into one

### ISSUE THREAD

**Issue by paulbsd** [factorfx/OpenNAS#3]
Cédric,

The script attached contains certain changes witch makes snaprepl.withoutcarp deprecated.
The $carpdev variable in snaprepl.conf is a switch when using carp or not
[snaprepl.txt](https://github.com/FactorFX/OpenNAS/files/132426/snaprepl.txt)

Just take a look

Cheers

**Comment by cedricdenis** [comment]
Hi Paulbsd,

It will be done

Thanks
