### ISSUE TITLE
Multiple network in /etc/exports

### ISSUE THREAD

**Issue by paulbsd** [factorfx/OpenNAS#5]
Hi Cédric,

When authorize one network (10.0.0.50/32) to use a NFS export the generated /etc/exports is the following : 
/mnt/TESTPOOL/dataset -mapall=root -network 10.0.0.50 -mask 255.255.255.255
In this case, the mountd process works, and the export is mountable.

When authorize multiple networks (10.0.0.50/32 and 10.0.0.60/32), the /etc/exports file is the following
/mnt/TESTPOOL/dataset -mapall=root -network 10.0.0.50/32 10.0.0.60 -mask 255.255.255.255
The syntax isn't correct and the mountd process fails.

I think that using one line per export per authorized network would be a convenient solution

Cheers

**Comment by cedricdenis** [comment]
Hi Paulbsd,

It will apllied in next release

Thanks
